version: "3"
services:
  frontend:
    build: ./
    command: sh -c "yarn run dev"
    container_name: "My_blog_Frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    stdin_open: true
    tty: true
    networks:
      external-my_blog_network:
        ipv4_address: 192.168.192.2
networks:
  external-my_blog_network:
    external: true
